language: python
python:
  - "3.5"
notifications:
  email: false

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # for debugging

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION nose --file=requirements.txt
  - source activate testenv
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=crowdastro

after_success:
  - coveralls
