site_name: crowdastro
pages:
  - Home: index.md
  - Setup: setup.md
  - Pipeline: pipeline.md
  - Notebooks: notebooks.md
  - ATLAS Data: datasets/atlas.md
  - Crowdastro Dataset: dataset.md
theme: readthedocs
