python3 -m crowdastro.import_data
python3 -m crowdastro.consensuses
python3 -m crowdastro.generate_training_data
python3 -m crowdastro.generate_image_patches
python3 -m crowdastro.compile_cnn
python3 -m crowdastro.train_cnn
python3 -m crowdastro.generate_cnn_outputs
python3 -m crowdastro.train_lr
python3 -m crowdastro.test_lr
